// AUTHENTICATION RELATED--
export const SET_THEME = 'SET_THEME';

// AUTHENTICATION RELATED--
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const GET_USER_DETAILS = 'GET_USER_DATAILS';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';
export const LOGOUT = 'LOGOUT';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';

export const SET_FAVORITES = 'SET_FAVORITES';
export const UPDATE_FAVORITE = 'UPDATE_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';

export const UPDATE_COUNTRY = 'UPDATE_COUNTRY';

export const EV_STATIONS = 'EV_STATIONS';
export const SET_RADIUS = 'SET_RADIUS';
export const TENANT = 'TENANT';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_CONNECTORS = 'SET_CONNECTORS';
export const SET_NETWORKS = 'SET_NETWORKS';
export const SET_CHARGING_SPEED = 'SET_CHARGING_SPEED';
export const SET_AVAILABLE_NOW = 'SET_AVAILABLE_NOW';
export const HOME_ROUTE = 'HOME_ROUTE';
export const KEYBOARD_OPEN = 'KEYBOARD_OPEN';

// BOOKMARK
export const BOOKMARK_ARTICLES = 'BOOKMARK_ARTICLES';
export const BOOKMARK_STATIONS = 'BOOKMARK_STATIONS';
export const BOOKMARK_CLASSIFIED = 'BOOKMARK_CLASSIFIED';
